# Generated by Django 3.2 on 2022-09-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taskschedule',
            options={},
        ),
        migrations.AlterModelTable(
            name='taskhost',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taskschedule',
            table=None,
        ),
    ]
