# Generated by Django 3.2 on 2022-09-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20220917_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhost',
            options={'verbose_name': '任务和主机的关系表', 'verbose_name_plural': '任务和主机的关系表'},
        ),
        migrations.AlterModelOptions(
            name='taskschedule',
            options={'verbose_name': '任务记录表', 'verbose_name_plural': '任务记录表'},
        ),
        migrations.AlterModelTable(
            name='taskhost',
            table='schedule_taskhost',
        ),
        migrations.AlterModelTable(
            name='taskschedule',
            table='schedule_taskschedule',
        ),
    ]
