# Generated by Django 3.2 on 2022-10-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20220917_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='period_way',
            field=models.IntegerField(choices=[(1, '普通计划任务'), (2, '定时一次任务'), (3, '周期计划任务')], default=1, verbose_name='任务周期方式'),
        ),
    ]
