# Generated by Django 3.2 on 2022-04-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bcomment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bread',
        ),
    ]
