# Generated by Django 3.2 on 2022-08-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conf_center', '0001_initial'),
        ('host', '0002_alter_pkeymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='conf_center.environment', verbose_name='从属环境'),
        ),
    ]
