# Generated by Django 3.2 on 2022-04-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0003_auto_20220417_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='drfdemo.Author', verbose_name='作者'),
        ),
    ]
