# Generated by Django 3.2 on 2022-07-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkeymodel',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
