# Generated by Django 3.2 on 2022-04-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0002_author_book_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_null',
            field=models.CharField(max_length=5, null=True, verbose_name='班级编号'),
        ),
    ]
