# Generated by Django 3.2 on 2022-03-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='tb_student',
        ),
    ]
