# Generated by Django 3.2 on 2022-03-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20220320_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.IntegerField(default=180),
        ),
    ]
