# Generated by Django 3.2 on 2022-03-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20220327_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='Py01', max_length=32),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='male', max_length=32),
        ),
    ]
